name: contrastive-av
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - cuda-version=12.8
  - cuda-driver-dev
  - cuda-cudart-dev
  - cuda-nvcc
  - accelerate
  - datasets
  - huggingface_hub
  - numpy
  - pandas
  - pip
  - prettytable
  - scikit-learn
  - scipy
  - setuptools
  - spacy
  - transformers
  - pip:
      - bitsandbytes==0.49.2
      - einops==0.8.2
      - freia==0.2
      - gitpython==3.1.47
      - jsonargparse==4.48.0
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lightning==2.6.1
      - lightning-utilities==0.15.3
      - pillow==12.0.0
      - pytorch-lightning==2.6.1
      - "jsonargparse[signatures]>=4.27.7"
      - pytorch-metric-learning==2.9.0
      - torchmetrics==1.9.0
      - wandb==0.26.1
