seed_everything: 1000

trainer:
  max_epochs: 10
  accelerator: auto
  devices: 1
  precision: bf16-mixed
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: contrastive-av
      entity: peterkirby
      log_model: true
      save_dir: output

model:
  class_path: models.transformer_classification_module.TransformerClassificationModule
  init_args:
    compile: true
    lr: 4e-5
    lr_schedule: linear
    warmup_ratio: 0.1
    negatives_per_positive: 1
    alpha: 0.5
    gamma: 0
    model_config:
      model_name_or_path: huawei-noah/TinyBERT_General_4L_312D
      attn_implementation: flash_attention_2

data:
  batch_size: 8
  eval_batch_size: 128
  sampler: mperclass
  m: 2
  num_threads: 12
  max_length: 512
  tokenizer_parallelism: false
  prefetch_factor: 1

