seed_everything: 42

trainer:
  max_epochs: 10
  accelerator: auto
  devices: 1
  precision: bf16-mixed

model:
  class_path: models.transformer_contrastive_module.TransformerContrastiveModule
  init_args:
    compile: false
    lr: 8e-5
    microbatch_size: 256
    model_config:
      model_name_or_path: huawei-noah/TinyBERT_General_4L_312D
      attn_implementation: flash_attention_2
      pooling: cls_concat
      concat_layers: 4
      head_type: ln_gelu_residual
      projection_hidden_dim: 2496
      normalize: true
      resize_token_embeddings: false

    loss_dict:
      name: ntxent

data:
  batch_size: 1024
  sampler: mperclass
  m: 2
  num_workers: 12
  max_length: 512
